declare namespace NodeJS {
    interface ProcessEnv {
        NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: string;
        NEXT_ANVIL_RPC_URL: string;
        NEXT_ALCHEMY_ZKSYNC_SEPOLIA_RPC_URL: string;
        NEXT_ALCHEMY_ZKSYNC_MAINNET_RPC_URL: string;
        NEXT_PUBLIC_FUND_ME_CONTRACT_ADDRESS_ANVIL: string;
        NEXT_PUBLIC_FUND_ME_CONTRACT_ADDRESS_ZKSYNCSEPOLIATESTNET: string;
        NEXT_PUBLIC_ZKTOKENS_CONTRACT_ADDRESS_ANVIL: string;
        NEXT_PUBLIC_ZKTOKENS_CONTRACT_ADDRESS_ZKSYNCSEPOLIATESTNET: string;
    }
}