declare namespace NodeJS {
    interface ProcessEnv {
        NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: string;
        NEXT_PUBLIC_FUND_ME_CONTRACT_ADDRESS_ANVIL: string;
        NEXT_PUBLIC_FUND_ME_CONTRACT_ADDRESS_ZKSYNCSEPOLIATESTNET: string;
        NEXT_PUBLIC_ZKTOKENS_CONTRACT_ADDRESS_ANVIL: string;
        NEXT_PUBLIC_ZKTOKENS_CONTRACT_ADDRESS_ZKSYNCSEPOLIATESTNET: string;
    }
}