[project]
src = "src"
out = "out"
dot_env = ".env"
dependencies = ["snekmate"]


# Default zktoken contract config
[networks.contracts.zktoken]
abi = "abis/ZKsync.json"
deployer_script = "script/mocks/deploy_mock_zk_token.py"

# Anvil network configuration
[networks.anvil]
url = "http://127.0.0.1:8545"
prompt_live = false
save_to_db = false
chain_id = 31337
default_account_name = "$DEFAULT_ACCOUNT_NAME"
unsafe_password_file = "$UNSAFE_PASSWORD_FILE"

# Anvil staging test configuration
[networks.anvil-staging]
url = "http://127.0.0.1:8545"
prompt_live = false
save_to_db = false
chain_id = 31337
default_account_name = "$DEFAULT_ACCOUNT_NAME"
unsafe_password_file = "$UNSAFE_PASSWORD_FILE"
live_or_staging = true

[networks.anvil-staging.contracts.fund_me]
# address = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" # @dev for frontend testing
deployer_script = "script/deploy_fund_me.py"

[networks.anvil-staging.contracts.zktoken]
# address = "0x5FbDB2315678afecb367f032d93F642f64180aa3" # @dev for frontend testing
deployer_script = "script/mocks/deploy_mock_zk_token.py"

# ZKSync fork configuration
[networks.zksync-fork]
fork = true
is_zksync = true
url = "$ZKSYNC_MAINNET_RPC_ALCHEMY"
chain_id = 324
default_account_name = "$DEFAULT_ACCOUNT_NAME"
unsafe_password_file = "$UNSAFE_PASSWORD_FILE"

[networks.zksync-fork.contracts.zktoken]
address = "$ZKSYNC_MAINNET_ZK_TOKEN_ADDRESS"

# ZKSync Sepolia configuration
[networks.zksync-sepolia]
is_zksync = true
url = "$ZKSYNC_SEPOLIA_RPC_ALCHEMY"
chain_id = 300
default_account_name = "$DEFAULT_ACCOUNT_NAME_ZKSYNC"
explorer_uri = "https://explorer.sepolia.era.zksync.dev"
explorer_type = "zksyncexplorer"
prompt_live = true
save_to_db = true
live_or_staging = true

[networks.zksync-sepolia.contracts.fund_me]
address = "$FUNDME_SEPOLIA_ADDRESS"

[networks.zksync-sepolia.contracts.zktoken]
address = "$ZKSYNC_SEPOLIA_ZK_TOKEN_CUSTOM_ADDRESS"

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
